import "@/styles/global.scss";
import type { Metadata } from "next";
import LayoutProvider from "./provider/layoutProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <LayoutProvider>{children}</LayoutProvider>
    </html>
  );
}
